apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodep-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodep
  template:
    metadata:
      labels:
        app: autodep
    spec:
      containers:
      - name: autodep-container
        image: 060795905397.dkr.ecr.us-east-1.amazonaws.com/autodep:latest
        ports:
        - containerPort: 80
